name: LibMarcaBone
main: com.github.mrmks.mc.marcabone.Marcabone
version: ${version}
commands:
  lmbr:
    description: reload build-in language files
    usage: <command>
    permission: lmb.perm.reload
permissions:
  lmb.perm.reload:
    default: op