name: DevToolsB
main: com.github.MrMks.dev_tools_b.DevToolsB
version: ${version}
commands:
  dtb:
    description: base command for plugin DevToolsB
    usage: '<sub> [args]'
    permission: devTools.*
permissions:
  devTools.reload:
    default: op
  devTools.*:
    children:
      - devTools.reload
    default: op